# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: 京喜工厂+京东工厂+京喜财富岛+合成月饼

on:
  workflow_dispatch:
  schedule:
    - cron: '40 */1 * * *'
  repository_dispatch:
    types: jd_dreamFactory
jobs:
  build:

    runs-on: ubuntu-latest
    if: github.event.repository.owner.id == github.event.sender.id
   
    steps:
     - uses: actions/checkout@v2
     - name: Use Node.js 15.x
       uses: actions/setup-node@v1
       with:
           node-version: 15.x 
     - name: npm install
       run: |
          npm install
     - name: '运行'
       run: |
          
          node jd_dreamFactory.js
          sleep 10
          node jd_jdfactory.js
          sleep 10
          node jd_cfd.js
          sleep 10
          node jd_cfd_mooncake.js
          
       env:
          JD_COOKIE: ${{ secrets.JD_COOKIE }}
          PUSH_PLUS_TOKEN: ${{ github.event.client_payload.PUSH_PLUS_TOKEN || secrets.PUSH_PLUS_TOKEN }}
          PUSH_PLUS_USER: ${{ github.event.client_payload.PUSH_PLUS_USER || secrets.PUSH_PLUS_USER }}
          JD_USER_AGENT: ${{ secrets.JD_USER_AGENT }}
          JD_DEBUG: ${{ secrets.JD_DEBUG }}
          PUSH_KEY: ${{ secrets.PUSH_KEY }}
          QQ_SKEY: ${{ secrets.QQ_SKEY }}
          QQ_MODE: ${{ secrets.QQ_MODE }}
          BARK_PUSH: ${{ secrets.BARK_PUSH }}
          TG_BOT_TOKEN: ${{ secrets.TG_BOT_TOKEN }}
          TG_USER_ID: ${{ secrets.TG_USER_ID }}
          BARK_SOUND: ${{ secrets.BARK_SOUND }}
          QYWX_KEY: ${{ secrets.QYWX_KEY }}
          QYWX_AM: ${{ secrets.QYWX_AM }}
          DREAM_FACTORY_SHARE_CODES: ${{ secrets.DREAM_FACTORY_SHARE_CODES }} #京喜工厂互助码环境变量
          JDCFD_SHARECODES: ${{ secrets.JDCFD_SHARECODES }} #财富岛互助码环境变量
          DDFACTORY_SHARECODES: ${{ secrets.DDFACTORY_SHARECODES }}
